language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip python-dev

install:
  - pip install coveralls --use-mirrors
  - pip install psutil --use-mirrors
  - pip install scrutinizer-ocular --use-mirrors

script:
  - export INTERPRETER=python
  - sbin/exabgp --version
  - sbin/exabgp --fi > etc/exabgp/exabgp.env
  - set pipefail
  - ./qa/bin/parsing
  - ./qa/bin/conversation
  - env ETC=`pwd`/etc/exabgp exabgp_log_enable=false nosetests --with-coverage ./qa/tests/*_test.py
#  - coverage run -m unittest discover -s qa/tests -p *_test.py

after_success:
  - coveralls
  - ocular

notifications:
  irc:
    channels: "irc.freenode.org#exabgp"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
  email: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/48936e41bd3f866cce4e
    # options: [always|never|change] default: always
    on_success: always
    on_failure: always
    on_start: false


# sudo: false
